-- Case-insensitive handle uniqueness.
--
-- The bug being fixed: the original UNIQUE constraint uses SQLite's
-- BINARY collation, so "alice", "Alice" and "ALICE" were three distinct
-- accounts, with three different keys and visually identical names. On a
-- network with no moderation, nobody is there to arbitrate an
-- impersonation: it has to be impossible, not arbitrable.
--
-- NOCASE only folds ASCII A-Z, which is exactly enough here:
-- validate_handle already only accepts restricted ASCII, precisely to
-- close the door on Unicode homoglyphs.
--
-- The casing chosen at registration is still displayed as-is -- "Alice"
-- displays with its capital letter. Only RE-registering a different
-- variant becomes impossible.
--
-- WARNING, this migration FAILS if the database already contains
-- collisions. That's intentional: silently renaming someone's account
-- would be worse than refusing to start. The server then stops with
-- SQLite's error message, and the administrator decides -- see
-- docs/ADMIN.md.

CREATE UNIQUE INDEX idx_users_handle_nocase ON users(handle COLLATE NOCASE);
