-- Unicite des pseudos insensible a la casse.
--
-- Le probleme corrige : la contrainte UNIQUE d'origine utilise la collation
-- BINARY de SQLite, donc "alice", "Alice" et "ALICE" etaient trois comptes
-- distincts, avec trois cles differentes et des noms visuellement identiques.
-- Sur un reseau sans moderation, personne n'est la pour arbitrer une
-- usurpation : il faut donc qu'elle soit impossible, pas arbitrable.
--
-- NOCASE ne replie que l'ASCII A-Z, ce qui suffit exactement ici :
-- validate_handle n'accepte deja que de l'ASCII restreint, precisement pour
-- fermer la porte aux homoglyphes Unicode.
--
-- La casse choisie a l'inscription reste affichee telle quelle -- "Alice"
-- s'affiche avec sa majuscule. Seule la REinscription d'une variante devient
-- impossible.
--
-- ATTENTION, cette migration ECHOUE si la base contient deja des collisions.
-- C'est voulu : renommer le compte de quelqu'un en silence serait pire que de
-- refuser de demarrer. Le serveur s'arrete alors avec le message d'erreur de
-- sqlite, et l'administrateur tranche lui-meme -- voir docs/ADMIN.md.

CREATE UNIQUE INDEX idx_users_handle_nocase ON users(handle COLLATE NOCASE);
