#pragma once

#include "server/config/server_config.hpp"

#include <string>
#include <string_view>
#include <vector>

namespace hypercom::server {

// Reading hypercom.conf. Minimal format:
//
//   # comment
//   [section]
//   key = value
//
// No JSON, no YAML, no TOML: a one-line-per-setting format has no parser to
// audit, and the file is edited by hand by a human, not generated by a
// machine.
//
// Every error is ACCUMULATED rather than reported at the first one: an
// administrator who made three typos wants all three at once, not three
// restarts.
struct config_error {
    std::size_t line_number = 0;
    std::string message;
};

[[nodiscard]] bool parse_config_text(std::string_view text, server_config &out,
                                     std::vector<config_error> &errors);

[[nodiscard]] bool parse_config_file(std::string const &path,
                                     server_config &out,
                                     std::vector<config_error> &errors);

// Renders the errors in a form directly printable to stderr.
[[nodiscard]] std::string
format_config_errors(std::string const &path,
                     std::vector<config_error> const &errors);

} // namespace hypercom::server
